### ISSUE TITLE
how to create a static library on macOS?

### ISSUE THREAD

**Issue by tessus** [lu-zero/crav1e#36]
How can I create a static `librav1e.a` on macOS?

**Comment by lu-zero** [comment]
As mentioned in the README.md `make` or `cargo build` will generate it.

You may use `make install` to install it, currently on `/usr/local/` is a valid destination target but it will change once we switch to `cargo-c` to build it.

Example:
```
$ make install
mkdir -p /usr/local/include/rav1e /usr/local/lib/pkgconfig
cp rav1e.pc /usr/local/lib/pkgconfig
cp target/release/librav1e.a /usr/local/lib
cp target/release/librav1e.dylib /usr/local/lib/librav1e.0.1.0.dylib
ln -sf /usr/local/lib/librav1e.0.1.0.dylib /usr/local/lib/librav1e.dylib
cp include/rav1e.h /usr/local/include/rav1e
```

**Comment by tessus** [comment]
Thank you for the reply. I checked the `build.rs` file and didn't see any static libs - only dylib.
Then in the readme the following did not mention .a either: _the library will be in `target/<debug or release>/librav1e.<so or dylib>`_

But yes, I missed that part:
```
# Build librav1e.a, rav1e.h and rav1e.pc
$ make
``` 

My bad and sorry for the noise.

**Comment by lu-zero** [comment]
No problem, I'll update `README.md` again during this week so it is good to note when to clarify.
