### ISSUE TITLE
Include path in the pkg-config file

### ISSUE THREAD

**Issue by jamrial** [lu-zero/crav1e#39]
It right now by default looks like

`incdir=/usr/local/include/rav1e`

I think it would be better if it was /usr/local/include, and have the library users include <rav1e/rav1e.h> instead in their project files. That way CFLAGS will not be bloated with extra unnecessary -I entries

**Comment by lu-zero** [comment]
The `-I` are needed otherwise it would break a number of `pkg-config` use-cases.
